name: compileJar

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-java@v1
      with:
        java-version: '1.8'
        architecture: x64
    - run: javac -d ./classes *.java && cd classes && jar cvf TextExcel.jar *
    - name: Jar file
      uses: actions/upload-artifact@v2
      with:
        name: TextExcel.jar
        path: TextExcel.jar
